namespace FluidSimu
{
    public class PneumaticModel
    {
        /// <summary>
        /// Determines the simulation mode.
        /// If true, elements respond to direct control.
        /// If false, elements follow their pre-loaded schedules.
        /// </summary>
        public bool IsInteractive { get; set; } = false;
        /// <summary>
        /// Pneumatic elements 
        /// </summary>
        private readonly List<IPneumaticElement> _elements = new();
        // Expose elements for the Logger
        public List<IPneumaticElement> Elements => _elements;

        /// <summary>
        /// Network connections
        /// </summary>
        private readonly Dictionary<int, Connector> _nodes = new();

        /// <summary>
        /// Charge data generated by flow
        /// </summary>
        private List<ChargeData> chargeDatas = new List<ChargeData>();
        public double GetCharge(int id)
        {
            double result = 0;
            foreach (var c in chargeDatas)
            {
                if (c.Id == id)
                {
                    if (double.IsNaN(c.dQ))
                        throw new ArgumentException($"Connection {c.Id} calculated NaN pressure");

                    result += c.dQ;

                }
            }
            return result;
        }
        public double DeltaT { get; private set; } = 1.0;
        public double LastMaxPressureDelta { get; private set; } = double.PositiveInfinity;
        public static PneumaticModel FromDto(SimulationModelDto dto)
        {
            var model = new PneumaticModel();
            int num = 1;

            Console.WriteLine($"Create elements for model '{dto.ModelName}'");
            foreach (var e in dto.Elements)
            {
                IPneumaticElement element = e.Type.ToLower() switch
                {
                    "pipe" => new PipeElement(e, num++),
                    "valve" => new ValveElement(e, num++),
                    "throttle" => new ThrottleElement(e, num++),
                    "checkvalve" => new CheckValveElement(e, num++),
                    "tank" => new TankElement(e, num++),
                    "exhaust" => new SupplyElement(e, num++, true),
                    "supply" => new SupplyElement(e, num++, false),
                    "epu" => new EpuElement(e, num++),
                    _ => throw new NotSupportedException($"Unknown element type {e.Type}")
                };

                model._elements.Add(element);
                Console.WriteLine(element.ToString());
            }

            // --- START: NEW VALIDATION LOGIC ---
            Console.WriteLine("\nValidating model integrity...");

            // Step 1: Expand shorthand connections first. This also validates format.
            var expandedConnections = ExpandAndValidateConnections(dto.Connections, out var connectionErrors);
            if (connectionErrors.Any())
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("FATAL: Invalid format in 'connections'. Halting execution.");
                foreach (var error in connectionErrors)
                {
                    Console.WriteLine($"  - {error}");
                }
                Console.ResetColor();
                throw new InvalidOperationException("Connection configuration is invalid.");
            }

            // Step 2: Validate that all elements used in the *expanded* connections are defined.
            var definedElementNames = new HashSet<string>(model._elements.Select(e => e.Name));
            var usedInConnectionNames = new HashSet<string>();
            var errors = new List<string>();

            foreach (var connectionStr in expandedConnections)
            {
                var namesInConnection = connectionStr.Split(new[] { ',', '=', '>' }, StringSplitOptions.RemoveEmptyEntries)
                                                     .Select(name => name.Trim());
                foreach (var name in namesInConnection)
                {
                    if (string.IsNullOrWhiteSpace(name)) continue;

                    usedInConnectionNames.Add(name); // Track all used elements
                    if (!definedElementNames.Contains(name))
                    {
                        errors.Add($"Element '{name}' used in connection is not defined in the 'elements' list.");
                    }
                }
            }
            // If there are any errors, report them and stop execution.
            if (errors.Any())
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("FATAL: Model validation failed. Halting execution.");
                // Use a HashSet to only show unique error messages
                foreach (var error in errors.Distinct())
                {
                    Console.WriteLine($"  - {error}");
                }
                Console.ResetColor();
                throw new InvalidOperationException("Model configuration is invalid. Please check the JSON file.");
            }


            // Step 3. Check for defined elements that are never used in any connection.
            var unusedElementNames = definedElementNames.Except(usedInConnectionNames);
            if (unusedElementNames.Any())
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("WARNING: The following elements are defined but not used in any connection:");
                foreach (var unusedName in unusedElementNames)
                {
                    Console.WriteLine($"  - '{unusedName}'");
                }
                Console.ResetColor();
            }
            else
            {
                Console.WriteLine("Model validation successful: All elements are defined and used.");
            }
            // --- END: NEW VALIDATION LOGIC ---

            num = 0;
            foreach (string nls in expandedConnections)
            {
                if (nls.Contains("=>")) // Check for directional connection
                {
                    string[] parts = nls.Split(new[] { "=>" }, StringSplitOptions.TrimEntries);
                    if (parts.Length != 2) continue;

                    var inlet = model._elements.FirstOrDefault(e => e.Name.Equals(parts[0]));
                    var directionalElement = model._elements.FirstOrDefault(e => e.Name.Equals(parts[1]));

                    if (inlet != null && directionalElement is IDirectionalElement cv)
                    {
                        // Use the new, simpler interface to just set the inlet
                        cv.SetDirection(inlet);

                        // Still create a normal connector for them
                        List<IPneumaticElement> lst = new() { inlet, directionalElement };
                        model._nodes.Add(num, new(lst, num));
                        num++;
                    }
                }
                else  // Handle normal, symmetrical connection
                {
                    string[] nl = nls.Split(',', StringSplitOptions.TrimEntries);
                    List<IPneumaticElement> lst = new();
                    foreach (string s in nl)
                    {
                        foreach (var node in model._elements)
                        {
                            if (node.Name.Equals(s))
                            {
                                lst.Add(node);
                                break;
                            }
                        }
                    }
                    if (lst.Count() > 0)
                    {
                        model._nodes.Add(num, new(lst, num));
                        num++;
                    }
                }
            }
            model.DumpConnetors();

            // After the main connection loop, add this block to register neighbors for ALL valve types
            foreach (var conn in model._nodes.Values)
            {
                foreach (var el in conn.Elements)
                {
                    // For regular valves
                    if (el is ValveElement v)
                    {
                        foreach (var neighbor in conn.Elements)
                        {
                            if (neighbor != v) v.RegisterNeighbor(neighbor);
                        }
                    }
                    // For check valves
                    else if (el is CheckValveElement cv)
                    {
                        foreach (var neighbor in conn.Elements)
                        {
                            if (neighbor != cv) cv.RegisterNeighbor(neighbor);
                        }
                    }
                    // Add EPU Neighbor 
                    else if (el is EpuElement epu)
                    {
                        foreach (var neighbor in conn.Elements)
                        {
                            if (neighbor != epu) epu.RegisterNeighbor(neighbor);
                        }
                    }
                }
            }

            Console.WriteLine("\nValidating model physics...");
            foreach (var element in model._elements.OfType<EpuElement>())
            {
                // Check if any of the EPU's direct neighbors is a supply.
                bool hasSupply = element.Neighbors.Any(n => n.Type == PneumaticType.supply);

                if (!hasSupply)
                {
                    // It's better to warn than to crash, as this might be intentional for a simplified model.
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.WriteLine($"WARNING: EPU '{element.Name}' is not connected to a 'Supply' element.");
                    Console.WriteLine("         It will act as a perfect pressure source, which may be physically unrealistic.");
                    Console.ResetColor();
                }
                else
                {
                    Console.WriteLine($"  - EPU '{element.Name}' has a valid supply connection.");
                }
            }

            return model;
        }
        private static List<string> ExpandAndValidateConnections(List<string> rawConnections, out List<string> errors)
        {
            var expandedConnections = new List<string>();
            errors = new List<string>();

            foreach (var connectionStr in rawConnections)
            {
                if (string.IsNullOrWhiteSpace(connectionStr))
                {
                    continue;
                }

                // Case 1: Check Valve Connection (e.g., "A => B")
                if (connectionStr.Contains("=>"))
                {
                    if (connectionStr.Contains(',') || connectionStr.Contains(':'))
                    {
                        errors.Add($"Invalid connection string \"{connectionStr}\": Check valve operator '=>' cannot be mixed with hub ':' or chain ',' shorthand.");
                        continue;
                    }
                    var parts = connectionStr.Split(new[] { "=>" }, StringSplitOptions.RemoveEmptyEntries).Select(p => p.Trim()).ToArray();
                    if (parts.Length != 2)
                    {
                        errors.Add($"Invalid check valve format in \"{connectionStr}\": Must be 'Element1 => Element2'.");
                        continue;
                    }
                    expandedConnections.Add(string.Join(" => ", parts));
                }
                // Case 2: Hub Connection (e.g., "A: B, C")
                else if (connectionStr.Contains(':'))
                {
                    var hubParts = connectionStr.Split(':').Select(p => p.Trim()).ToArray();
                    if (hubParts.Length != 2 || string.IsNullOrWhiteSpace(hubParts[0]) || string.IsNullOrWhiteSpace(hubParts[1]))
                    {
                        errors.Add($"Invalid hub format in \"{connectionStr}\": Must be 'Hub: Spoke1, Spoke2, ...'.");
                        continue;
                    }

                    var hub = hubParts[0];
                    if (hub.Contains(','))
                    {
                        errors.Add($"Invalid hub format in \"{connectionStr}\": Only one element can be the hub (left of ':').");
                        continue;
                    }

                    var spokes = hubParts[1].Split(',').Select(s => s.Trim()).Where(s => !string.IsNullOrWhiteSpace(s)).ToArray();
                    if (spokes.Length < 1)
                    {
                        errors.Add($"Invalid hub format in \"{connectionStr}\": Hub must connect to at least one spoke.");
                        continue;
                    }

                    foreach (var spoke in spokes)
                    {
                        expandedConnections.Add($"{hub},{spoke}");
                    }
                }
                // Case 3: Chain or Simple Connection (e.g., "A, B, C")
                else if (connectionStr.Contains(','))
                {
                    var elements = connectionStr.Split(',').Select(s => s.Trim()).Where(s => !string.IsNullOrWhiteSpace(s)).ToArray();
                    if (elements.Length < 2)
                    {
                        errors.Add($"Invalid chain format in \"{connectionStr}\": Must contain at least two elements.");
                        continue;
                    }

                    for (int i = 0; i < elements.Length - 1; i++)
                    {
                        expandedConnections.Add($"{elements[i]},{elements[i + 1]}");
                    }
                }
                // Case 4: Invalid format
                else
                {
                    errors.Add($"Invalid connection string \"{connectionStr}\": Must be a pair ('A, B'), chain ('A, B, C'), hub ('A: B, C'), or check valve ('A => B').");
                }
            }

            return expandedConnections;
        }
        public void AddCharge(ChargeData x)
        {
            chargeDatas.Add(x);
        }
        public void ResetChargeData() { chargeDatas.Clear(); }
        private void CalcFlow(PneumaticModel model)
        {
            foreach (var c in _nodes.Keys)
                _nodes[c].CalcFlow(model);
        }
        public double ApplyProfile(ExecutionProfileDto profile)
        {
            bool hasValve = false;
            bool hasEpu = false;

            Console.WriteLine("\nApplying execution profile and validating schedules...");

            foreach (var element in _elements)
            {
                if (element is EpuElement epu)
                {
                    hasEpu = true;
                    // Try to get the timeline for the EPU by its name.
                    if (profile.EpuTimelines.TryGetValue(epu.Name, out var timeline))
                    {
                        // The timeline exists, now check if it's valid.
                        if (timeline == null || timeline.Count == 0)
                        {
                            // Case 1: The timeline is empty.
                            Console.ForegroundColor = ConsoleColor.Yellow;
                            Console.WriteLine($"WARNING: The timeline for EPU '{epu.Name}' is empty. It will remain at its initial pressure.");
                            Console.ResetColor();
                        }
                        else if (timeline.All(e => Math.Abs(e.TargetPressure) < 1e-9))
                        {
                            // Case 2: The timeline exists but all values are zero. THIS IS THE KEY CHECK.
                            Console.ForegroundColor = ConsoleColor.Red;
                            Console.WriteLine($"ERROR: The timeline for EPU '{epu.Name}' was found, but all target pressures are zero.");
                            Console.WriteLine("         This is likely caused by a typo in the execution profile JSON.");
                            Console.WriteLine("         HINT: Please ensure you are using '\"targetPressure\"' as the property name.");
                            Console.ResetColor();
                        }
                        else
                        {
                            // The timeline is valid. Set the schedule.
                            Console.WriteLine($"  - Valid schedule found and applied for EPU '{epu.Name}'.");
                            epu.SetSchedule(timeline);
                        }
                    }
                    else
                    {
                        // Case 3: No timeline found for this EPU at all.
                        Console.ForegroundColor = ConsoleColor.Yellow;
                        Console.WriteLine($"WARNING: EPU '{epu.Name}' exists but has no timeline in the execution profile. It will remain at its initial pressure.");
                        Console.ResetColor();
                    }
                }
                // If element is Valve, look for schedule
                else if (element is ValveElement valve)
                {
                    hasValve = true;
                    if (profile.ValveTimelines.TryGetValue(valve.Name, out var timeline))
                    {
                        valve.SetSchedule(timeline);
                    }
                }
            }

            double lastEvent = 0;

            if (hasValve)
                lastEvent = profile.GetLastValveEventTime();

            if (hasEpu)
            {
                double dt = profile.GetLastEpuEventTime();
                if (dt > lastEvent)
                    lastEvent = dt;
            }
            return lastEvent;
        }
        public double CurrentTime { get; private set; } = 0;
        public void Reset(double dt)
        {
            DeltaT = dt;
            CurrentTime = 0;
        }
        public void Execute()
        {
            // Reset Charge Data
            ResetChargeData();

            // Calculate Flow (Physics)
            CalcFlow(this);

            // Update Pressures and find the maximum change
            double maxDelta = 0.0;

            foreach (var element in _elements)
            {
                double delta = element.CalcPressure(this);
                if (delta > maxDelta)
                    maxDelta = delta;
            }

            LastMaxPressureDelta = maxDelta;

            CurrentTime += DeltaT;
        }
        private void DumpConnetors()
        {
            Console.WriteLine($"\nConnection between elements");
            foreach (var c in _nodes.Keys)
            {
                Console.Write($"Node #{c}:\t");
                Connector? con;
                if (_nodes.TryGetValue(c, out con))
                {
                    Console.WriteLine(con.Info());
                }
                else
                    Console.WriteLine("failed!");
            }
        }
    }
}