namespace FluidSimu
{
    public class PneumaticModel
    {
        /// <summary>
        /// Determines the simulation mode.
        /// If true, elements respond to direct control.
        /// If false, elements follow their pre-loaded schedules.
        /// </summary>
        public bool IsInteractive { get; set; } = false;
        /// <summary>
        /// Pneumatic elements 
        /// </summary>
        private readonly List<IPneumaticElement> _elements = new();
        // Expose elements for the Logger
        public List<IPneumaticElement> Elements => _elements;

        /// <summary>
        /// Charge data generated by flow
        /// </summary>
        private List<ChargeData> chargeDatas = new List<ChargeData>();
        public double GetCharge(int id)
        {
            double result = 0;
            foreach (var c in chargeDatas)
            {
                if (c.Id == id)
                {
                    if (double.IsNaN(c.dQ))
                        throw new ArgumentException($"Connection {c.Id} calculated NaN pressure");

                    result += c.dQ;

                }
            }
            return result;
        }
        public double DeltaT { get; private set; } = 1.0;
        public double LastMaxPressureDelta { get; private set; } = double.PositiveInfinity;
        public static PneumaticModel FromDto(SimulationModelDto dto)
        {
            var model = new PneumaticModel();
            int num = 1;

            Console.WriteLine($"Create elements for model '{dto.ModelName}'");
            foreach (var e in dto.Elements)
            {
                IPneumaticElement element = e.Type.ToLower() switch
                {
                    "pipe" => new PipeElement(e, num++),
                    "valve" => new ValveElement(e, num++),
                    "throttle" => new ThrottleElement(e, num++),
                    "checkvalve" => new CheckValveElement(e, num++),
                    "tank" => new TankElement(e, num++),
                    "exhaust" => new SupplyElement(e, num++, true),
                    "supply" => new SupplyElement(e, num++, false),
                    "epu" => new EpuElement(e, num++),
                    _ => throw new NotSupportedException($"Unknown element type {e.Type}")
                };

                model._elements.Add(element);
                Console.WriteLine(element.ToString());
            }

            // --- START: NEW VALIDATION LOGIC ---
            Console.WriteLine("\nValidating model integrity...");
            var definedElementNames = new HashSet<string>(model._elements.Select(e => e.Name));
            var usedInConnectionNames = new HashSet<string>();
            var errors = new List<string>();

            // 1. Check if elements used in connections are actually defined.
            foreach (var connectionStr in dto.Connections)
            {
                var connectorParts = connectionStr.Split(',').Select(p => p.Trim());
                foreach (var part in connectorParts)
                {
                    var elementName = part.Split('.')[0];
                    if (string.IsNullOrWhiteSpace(elementName)) continue;

                    usedInConnectionNames.Add(elementName); // Track all used elements
                    if (!definedElementNames.Contains(elementName))
                    {
                        errors.Add($"Element '{elementName}' used in connection \"{connectionStr}\" is not defined in the 'elements' list.");
                    }
                }
            }

            // If there are any errors, report them and stop execution.
            if (errors.Any())
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("FATAL: Model validation failed. Halting execution.");
                foreach (var error in errors)
                {
                    Console.WriteLine($"  - {error}");
                }
                Console.ResetColor();
                throw new InvalidOperationException("Model configuration is invalid. Please check the JSON file.");
            }

            // 2. Check for defined elements that are never used in any connection.
            var unusedElementNames = definedElementNames.Except(usedInConnectionNames);
            if (unusedElementNames.Any())
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("WARNING: The following elements are defined but not used in any connection:");
                foreach (var unusedName in unusedElementNames)
                {
                    Console.WriteLine($"  - '{unusedName}'");
                }
                Console.ResetColor();
            }
            else
            {
                Console.WriteLine("Model validation successful: All elements are defined and used.");
            }
            // --- END: NEW VALIDATION LOGIC ---

            Console.WriteLine("\nProcessing connections...");
            foreach (var connectionStr in dto.Connections)
            {
                var parts = connectionStr.Split(',').Select(p => p.Trim()).ToList();
                if (parts.Count != 2)
                {
                    errors.Add($"Invalid connection format: \"{connectionStr}\". Each connection must be a pair of two connectors, e.g., 'P1.1, T1.1'.");
                    continue;
                }

                var (element1, connector1) = ParseConnectorString(parts[0], model._elements, errors);
                var (element2, connector2) = ParseConnectorString(parts[1], model._elements, errors);

                if (element1 != null && element2 != null && connector1 != null && connector2 != null)
                {
                    if (element1 is BaseElement be1 && element2 is BaseElement be2)
                    {
                        be1.AddConnection(connector1, element2);
                        be2.AddConnection(connector2, element1);
                        Console.WriteLine($"  - Connected {element1.Name}.{connector1} to {element2.Name}.{connector2}");
                    }
                }
            }

            if (errors.Any())
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("FATAL: Model connection processing failed. Halting execution.");
                foreach (var error in errors)
                {
                    Console.WriteLine($"  - {error}");
                }
                Console.ResetColor();
                throw new InvalidOperationException("Model configuration is invalid. Please check the JSON file.");
            }
            Console.WriteLine("\nValidating model physics...");
            foreach (var element in model._elements.OfType<EpuElement>())
            {
                // Check if any of the EPU's direct neighbors is a supply.
                bool hasSupply = element.Connections.Values.Any(n => n.Type == PneumaticType.supply);

                if (!hasSupply)
                {
                    // It's better to warn than to crash, as this might be intentional for a simplified model.
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.WriteLine($"WARNING: EPU '{element.Name}' is not connected to a 'Supply' element.");
                    Console.WriteLine("         It will act as a perfect pressure source, which may be physically unrealistic.");
                    Console.ResetColor();
                }
                else
                {
                    Console.WriteLine($"  - EPU '{element.Name}' has a valid supply connection.");
                }
            }
            return model;
        }
        private static (IPneumaticElement? element, string? connector) ParseConnectorString(string connectorStr, List<IPneumaticElement> elements, List<string> errors)
        {
            var parts = connectorStr.Split('.');
            var elementName = parts[0];
            var connectorName = parts.Length > 1 ? parts[1] : "1"; // Default to "1" if not specified

            var element = elements.FirstOrDefault(e => e.Name.Equals(elementName));

            if (element == null)
            {
                errors.Add($"Element '{elementName}' in connection \"{connectorStr}\" is not defined.");
                return (null, null);
            }
            if (element is BaseElement be && !be.ValidConnectorNames.Contains(connectorName))
            {
                errors.Add($"Connector '{connectorName}' is not valid for element '{elementName}' of type '{element.Type}'. Valid connectors are: {string.Join(", ", be.ValidConnectorNames)}.");
                return (null, null);
            }
            return (element, connectorName);
        }
        public void AddCharge(ChargeData x)
        {
            chargeDatas.Add(x);
        }
        public void ResetChargeData() { chargeDatas.Clear(); }
        private void CalcFlow(PneumaticModel model)
        {
            foreach (var element in _elements)
            {
                element.CalcFlow(model);
            }
        }
        public double ApplyProfile(ExecutionProfileDto profile)
        {
            bool hasValve = false;
            bool hasEpu = false;

            Console.WriteLine("\nApplying execution profile and validating schedules...");

            foreach (var element in _elements)
            {
                if (element is EpuElement epu)
                {
                    hasEpu = true;
                    // Try to get the timeline for the EPU by its name.
                    if (profile.EpuTimelines.TryGetValue(epu.Name, out var timeline))
                    {
                        // The timeline exists, now check if it's valid.
                        if (timeline == null || timeline.Count == 0)
                        {
                            // Case 1: The timeline is empty.
                            Console.ForegroundColor = ConsoleColor.Yellow;
                            Console.WriteLine($"WARNING: The timeline for EPU '{epu.Name}' is empty. It will remain at its initial pressure.");
                            Console.ResetColor();
                        }
                        else if (timeline.All(e => Math.Abs(e.TargetPressure) < 1e-9))
                        {
                            // Case 2: The timeline exists but all values are zero. THIS IS THE KEY CHECK.
                            Console.ForegroundColor = ConsoleColor.Red;
                            Console.WriteLine($"ERROR: The timeline for EPU '{epu.Name}' was found, but all target pressures are zero.");
                            Console.WriteLine("         This is likely caused by a typo in the execution profile JSON.");
                            Console.WriteLine("         HINT: Please ensure you are using '\"targetPressure\"' as the property name.");
                            Console.ResetColor();
                        }
                        else
                        {
                            // The timeline is valid. Set the schedule.
                            Console.WriteLine($"  - Valid schedule found and applied for EPU '{epu.Name}'.");
                            epu.SetSchedule(timeline);
                        }
                    }
                    else
                    {
                        // Case 3: No timeline found for this EPU at all.
                        Console.ForegroundColor = ConsoleColor.Yellow;
                        Console.WriteLine($"WARNING: EPU '{epu.Name}' exists but has no timeline in the execution profile. It will remain at its initial pressure.");
                        Console.ResetColor();
                    }
                }
                // If element is Valve, look for schedule
                else if (element is ValveElement valve)
                {
                    hasValve = true;
                    if (profile.ValveTimelines.TryGetValue(valve.Name, out var timeline))
                    {
                        valve.SetSchedule(timeline);
                    }
                }
            }

            double lastEvent = 0;

            if (hasValve)
                lastEvent = profile.GetLastValveEventTime();

            if (hasEpu)
            {
                double dt = profile.GetLastEpuEventTime();
                if (dt > lastEvent)
                    lastEvent = dt;
            }
            return lastEvent;
        }
        public double CurrentTime { get; private set; } = 0;
        public void Reset(double dt)
        {
            DeltaT = dt;
            CurrentTime = 0;
        }
        public void Execute()
        {
            // Reset Charge Data
            ResetChargeData();

            // Calculate Flow (Physics)
            CalcFlow(this);

            // Update Pressures and find the maximum change
            double maxDelta = 0.0;

            foreach (var element in _elements)
            {
                double delta = element.CalcPressure(this);
                if (delta > maxDelta)
                    maxDelta = delta;
            }

            LastMaxPressureDelta = maxDelta;

            CurrentTime += DeltaT;
        }
    }
}